# NIFTY Midcap 100 constituents with index weights (as published Sep 2026).
# symbol = NSE symbol, yahoo = Yahoo Finance ticker, weight = index weight %.
# Edit this list to change what the scanner watches.

TICKERS = [
    ("IDEA",       "Vodafone Idea",                     2.34),
    ("BHEL",       "Bharat Heavy Electricals",          2.17),
    ("POWERINDIA", "Hitachi Energy India",              2.03),
    ("BSE",        "BSE Ltd",                           2.00),
    ("GROWW",      "Billionbrains Garage (Groww)",      1.82),
    ("POLYCAB",    "Polycab India",                     1.80),
    ("LENSKART",   "Lenskart Solutions",                1.72),
    ("GVT&D",      "GE Vernova T&D India",              1.68),
    ("PAYTM",      "One97 Communications",              1.68),
    ("INDIANB",    "Indian Bank",                       1.66),
    ("ABCAPITAL",  "Aditya Birla Capital",              1.58),
    ("LAURUSLABS", "Laurus Labs",                       1.54),
    ("HEROMOTOCO", "Hero MotoCorp",                     1.51),
    ("MARICO",     "Marico",                            1.51),
    ("GMRAIRPORT", "GMR Airports",                      1.50),
    ("OFSS",       "Oracle Financial Services",         1.48),
    ("INDUSTOWER", "Indus Towers",                      1.48),
    ("NYKAA",      "FSN E-Commerce (Nykaa)",            1.42),
    ("AUROPHARMA", "Aurobindo Pharma",                  1.39),
    ("JSWENERGY",  "JSW Energy",                        1.39),
    ("ASHOKLEY",   "Ashok Leyland",                     1.39),
    ("LUPIN",      "Lupin",                             1.39),
    ("MANKIND",    "Mankind Pharma",                    1.36),
    ("BHARATFORG", "Bharat Forge",                      1.34),
    ("PERSISTENT", "Persistent Systems",                1.26),
    ("FEDERALBNK", "Federal Bank",                      1.23),
    ("MCX",        "Multi Commodity Exchange",          1.21),
    ("POLICYBZR",  "PB Fintech",                        1.20),
    ("DIXON",      "Dixon Technologies",                1.19),
    ("COFORGE",    "Coforge",                           1.18),
    ("NAUKRI",     "Info Edge (India)",                 1.17),
    ("AUBANK",     "AU Small Finance Bank",             1.15),
    ("OIL",        "Oil India",                         1.15),
    ("LTF",        "L&T Finance",                       1.12),
    ("SWIGGY",     "Swiggy",                            1.11),
    ("NHPC",       "NHPC",                              1.11),
    ("INDUSINDBK", "IndusInd Bank",                     1.10),
    ("WAAREEENER", "Waaree Energies",                   1.09),
    ("HINDPETRO",  "Hindustan Petroleum",               1.08),
    ("IDFCFIRSTB", "IDFC First Bank",                   1.08),
    ("SAIL",       "Steel Authority of India",          1.07),
    ("YESBANK",    "Yes Bank",                          1.07),
    ("SRF",        "SRF",                               1.06),
    ("ICICIGI",    "ICICI Lombard General Insurance",   1.05),
    ("NMDC",       "NMDC",                              1.05),
    ("HAVELLS",    "Havells India",                     1.01),
    ("GLENMARK",   "Glenmark Pharmaceuticals",          0.99),
    ("PHOENIXLTD", "Phoenix Mills",                     0.98),
    ("FORTIS",     "Fortis Healthcare",                 0.97),
    ("DABUR",      "Dabur India",                       0.97),
    ("NATIONALUM", "National Aluminium",                0.96),
    ("ATGL",       "Adani Total Gas",                   0.95),
    ("PRESTIGE",   "Prestige Estates Projects",         0.94),
    ("BIOCON",     "Biocon",                            0.92),
    ("BANKINDIA",  "Bank of India",                     0.92),
    ("OBEROIRLTY", "Oberoi Realty",                     0.92),
    ("SBICARD",    "SBI Cards & Payment Services",      0.90),
    ("KALYANKJIL", "Kalyan Jewellers India",            0.90),
    ("MOTILALOFS", "Motilal Oswal Financial",           0.89),
    ("ALKEM",      "Alkem Laboratories",                0.88),
    ("SUZLON",     "Suzlon Energy",                     0.88),
    ("APLAPOLLO",  "APL Apollo Tubes",                  0.86),
    ("RADICO",     "Radico Khaitan",                    0.85),
    ("COROMANDEL", "Coromandel International",          0.82),
    ("MRF",        "MRF",                               0.79),
    ("GODREJPROP", "Godrej Properties",                 0.76),
    ("MFSL",       "Max Financial Services",            0.74),
    ("TIINDIA",    "Tube Investments of India",         0.73),
    ("TATACOMM",   "Tata Communications",               0.73),
    ("M&MFIN",     "M&M Financial Services",            0.72),
    ("COLPAL",     "Colgate-Palmolive India",           0.71),
    ("UPL",        "UPL",                               0.70),
    ("VMM",        "Vishal Mega Mart",                  0.69),
    ("360ONE",     "360 One WAM",                       0.64),
    ("PREMIERENE", "Premier Energies",                  0.64),
    ("MPHASIS",    "Mphasis",                           0.63),
    ("KEI",        "KEI Industries",                    0.63),
    ("BDL",        "Bharat Dynamics",                   0.63),
    ("SUPREMEIND", "Supreme Industries",                0.62),
    ("RVNL",       "Rail Vikas Nigam",                  0.62),
    ("PAGEIND",    "Page Industries",                   0.57),
    ("VOLTAS",     "Voltas",                            0.56),
    ("CONCOR",     "Container Corporation of India",    0.55),
    ("ASTRAL",     "Astral",                            0.55),
    ("PATANJALI",  "Patanjali Foods",                   0.54),
    ("IRCTC",      "Indian Railway Catering & Tourism", 0.54),
    ("COCHINSHIP", "Cochin Shipyard",                   0.53),
    ("EXIDEIND",   "Exide Industries",                  0.51),
    ("HUDCO",      "Housing & Urban Development Corp",  0.50),
    ("PIIND",      "PI Industries",                     0.50),
    ("TATAINVEST", "Tata Investment Corporation",       0.48),
    ("BLUESTARCO", "Blue Star",                         0.46),
    ("IREDA",      "Indian Renewable Energy Dev Agency",0.45),
    ("JUBLFOOD",   "Jubilant FoodWorks",                0.45),
    ("LICHSGFIN",  "LIC Housing Finance",               0.45),
    ("GODFRYPHLP", "Godfrey Phillips India",            0.44),
    ("TATAELXSI",  "Tata Elxsi",                        0.31),
    ("KPITTECH",   "KPIT Technologies",                 0.22),
]


# Yahoo Finance uses a different ticker for a handful of names (renames, new
# listings). Add an entry here whenever the scan report says a symbol had no
# data -- look the company up on finance.yahoo.com and paste its ticker.
YAHOO_OVERRIDES = {
    # "NSE SYMBOL": "YAHOO TICKER",
}


def yahoo_symbol(nse_symbol: str) -> str:
    """NSE symbol -> Yahoo Finance ticker. yfinance handles URL encoding."""
    if nse_symbol in YAHOO_OVERRIDES:
        return YAHOO_OVERRIDES[nse_symbol]
    return nse_symbol + ".NS"
